{
    'name': 'Shakti Product Master',
    'version': '17.0.1.0.0',
    'category': 'Inventory/Products',
    'summary': 'Product master fields with auto name/code generation via category sequence',
    'author': 'Hetvi Jesadiya',
    'website': 'http://www.teknovativesolution.com/',
    'depends': ['base','product'],
    'data': [
        'security/ir.model.access.csv',
        
        'views/product_category_views.xml',
        'views/product_template_views.xml',
        'views/shakti_additional_process_views.xml',
        'views/shakti_customer_code_views.xml',
        'views/shakti_die_code_views.xml',
        'views/shakti_end_connection_views.xml',
        'views/shakti_fitting_standard_views.xml',
        'views/shakti_item_group_views.xml',
        'views/shakti_material_grade_views.xml',
        'views/shakti_process_code_views.xml',
        'views/shakti_sch_views.xml',
        'views/shakti_size1_views.xml',
        'views/shakti_size2_views.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
